#version: '3.8'

services:
  vectordb:
    image: qdrant/qdrant:latest
    ports:
     - "6333"

  backend:
       # Adjust this path to the directory of your backend Dockerfile
    #image: backend1 
    build:
      context: ./Speaker_Backend 
      dockerfile: Dockerfile # Tag your Speaker_Backend image as 'backend1'
    ports:
      - "8000"
    depends_on:
      - vectordb
    #volumes:
     # - ./Speaker_Backend:/app

  frontend:
     # Adjust this path to the directory of your frontend Dockerfile
    #image: frontend1 
    build:
      context: ./Speaker_Frontend 
      dockerfile: Dockerfile # Tag your Speaker_Frontend image as 'frontend1'
    ports:
      - "7860:7860"
    depends_on:
      - backend
    volumes:
      - ./Speaker_Frontend:/app


